from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable


@dataclass(frozen=True)
class MetricSpec:
    key: str
    panel: str
    json_path: tuple[str, ...]
    label: str
    color: str
    kind: str
    cli_group: str
    source: str
    linewidth: float = 1.0
    alpha: float = 1.0
    negative_color: str | None = None


@dataclass(frozen=True)
class PanelSpec:
    key: str
    order: int
    ylabel: str | None = None
    y_limits: tuple[float, float] | None = None
    reference_lines: tuple[float, ...] = ()


PANEL_REGISTRY: tuple[PanelSpec, ...] = (
    PanelSpec(key="PRICE", order=0, ylabel="Price"),
    PanelSpec(key="RSI", order=1, ylabel="RSI(14)", y_limits=(0.0, 100.0), reference_lines=(70.0, 30.0)),
    PanelSpec(key="MACD", order=2, ylabel="MACD", reference_lines=(0.0,)),
    PanelSpec(key="ADX", order=3, ylabel="ADX(14)"),
    PanelSpec(key="OBV", order=4, ylabel="OBV"),
    PanelSpec(key="DEALER", order=5, ylabel="Dealer"),
    PanelSpec(key="VOL", order=6, ylabel="Volatility"),
)

PANEL_SPECS = {panel.key: panel for panel in PANEL_REGISTRY}
PANEL_ORDER = tuple(panel.key for panel in sorted(PANEL_REGISTRY, key=lambda item: item.order))

COLOR_MOMENTUM = "#1f77b4"
COLOR_TREND = "#2ca02c"
COLOR_VOLATILITY = "#ff7f0e"
COLOR_VOLUME = "#9467bd"
COLOR_OTHERS = "#8c564b"

CLI_GROUP_ALIASES = {
    "MA": {"SMA20", "SMA50", "SMA200"},
    "RSI": {"RSI"},
    "MACD": {"MACD", "MACD_SIGNAL", "MACD_HIST"},
    "ADX": {"ADX"},
    "OBV": {"OBV"},
    "DEALER": {"GEX_NET", "GEX_TOTAL", "DGPI"},
    "VOL": {"AVG_IV", "IV_RANK"},
}


METRIC_REGISTRY: tuple[MetricSpec, ...] = (
    MetricSpec(
        key="AWESOME_OSCILLATOR",
        panel="MOMENTUM",
        json_path=("momentum", "awesome_oscillator", "awesome_oscillator"),
        label="AWESOME_OSCILLATOR",
        color=COLOR_MOMENTUM,
        kind="line",
        cli_group="MOMENTUM",
        source="technical",
    ),
    MetricSpec(
        key="KAMA",
        panel="MOMENTUM",
        json_path=("momentum", "kama", "kama"),
        label="KAMA",
        color=COLOR_MOMENTUM,
        kind="line",
        cli_group="MOMENTUM",
        source="technical",
    ),
    MetricSpec(
        key="PPO",
        panel="MOMENTUM",
        json_path=("momentum", "ppo", "ppo"),
        label="PPO",
        color=COLOR_MOMENTUM,
        kind="line",
        cli_group="MOMENTUM",
        source="technical",
    ),
    MetricSpec(
        key="PPO_SIGNAL",
        panel="MOMENTUM",
        json_path=("momentum", "ppo", "ppo_signal"),
        label="PPO_SIGNAL",
        color=COLOR_MOMENTUM,
        kind="line",
        cli_group="MOMENTUM",
        source="technical",
    ),
    MetricSpec(
        key="PPO_HIST",
        panel="MOMENTUM",
        json_path=("momentum", "ppo", "ppo_hist"),
        label="PPO_HIST",
        color=COLOR_MOMENTUM,
        kind="hist",
        cli_group="MOMENTUM",
        source="technical",
        alpha=0.4,
        negative_color="#d62728",
    ),
    MetricSpec(
        key="PVO",
        panel="MOMENTUM",
        json_path=("momentum", "pvo", "pvo"),
        label="PVO",
        color=COLOR_MOMENTUM,
        kind="line",
        cli_group="MOMENTUM",
        source="technical",
    ),
    MetricSpec(
        key="PVO_SIGNAL",
        panel="MOMENTUM",
        json_path=("momentum", "pvo", "pvo_signal"),
        label="PVO_SIGNAL",
        color=COLOR_MOMENTUM,
        kind="line",
        cli_group="MOMENTUM",
        source="technical",
    ),
    MetricSpec(
        key="PVO_HIST",
        panel="MOMENTUM",
        json_path=("momentum", "pvo", "pvo_hist"),
        label="PVO_HIST",
        color=COLOR_MOMENTUM,
        kind="hist",
        cli_group="MOMENTUM",
        source="technical",
        alpha=0.4,
        negative_color="#d62728",
    ),
    MetricSpec(
        key="ROC",
        panel="MOMENTUM",
        json_path=("momentum", "roc", "roc"),
        label="ROC",
        color=COLOR_MOMENTUM,
        kind="line",
        cli_group="MOMENTUM",
        source="technical",
    ),
    MetricSpec(
        key="RSI",
        panel="RSI",
        json_path=("momentum", "rsi", "rsi"),
        label="RSI",
        color="#1f77b4",
        kind="line",
        cli_group="MOMENTUM",
        source="technical",
    ),
    MetricSpec(
        key="STOCHRSI",
        panel="MOMENTUM",
        json_path=("momentum", "stochrsi", "stochrsi"),
        label="STOCHRSI",
        color=COLOR_MOMENTUM,
        kind="line",
        cli_group="MOMENTUM",
        source="technical",
    ),
    MetricSpec(
        key="STOCHRSI_K",
        panel="MOMENTUM",
        json_path=("momentum", "stochrsi", "stochrsi_k"),
        label="STOCHRSI_K",
        color=COLOR_MOMENTUM,
        kind="line",
        cli_group="MOMENTUM",
        source="technical",
    ),
    MetricSpec(
        key="STOCHRSI_D",
        panel="MOMENTUM",
        json_path=("momentum", "stochrsi", "stochrsi_d"),
        label="STOCHRSI_D",
        color=COLOR_MOMENTUM,
        kind="line",
        cli_group="MOMENTUM",
        source="technical",
    ),
    MetricSpec(
        key="STOCH",
        panel="MOMENTUM",
        json_path=("momentum", "stoch", "stoch"),
        label="STOCH",
        color=COLOR_MOMENTUM,
        kind="line",
        cli_group="MOMENTUM",
        source="technical",
    ),
    MetricSpec(
        key="STOCH_SIGNAL",
        panel="MOMENTUM",
        json_path=("momentum", "stoch", "stoch_signal"),
        label="STOCH_SIGNAL",
        color=COLOR_MOMENTUM,
        kind="line",
        cli_group="MOMENTUM",
        source="technical",
    ),
    MetricSpec(
        key="TSI",
        panel="MOMENTUM",
        json_path=("momentum", "tsi", "tsi"),
        label="TSI",
        color=COLOR_MOMENTUM,
        kind="line",
        cli_group="MOMENTUM",
        source="technical",
    ),
    MetricSpec(
        key="ULTIMATE_OSCILLATOR",
        panel="MOMENTUM",
        json_path=("momentum", "ultimate_oscillator", "ultimate_oscillator"),
        label="ULTIMATE_OSCILLATOR",
        color=COLOR_MOMENTUM,
        kind="line",
        cli_group="MOMENTUM",
        source="technical",
    ),
    MetricSpec(
        key="WILLIAMS_R",
        panel="MOMENTUM",
        json_path=("momentum", "williams_r", "williams_r"),
        label="WILLIAMS_R",
        color=COLOR_MOMENTUM,
        kind="line",
        cli_group="MOMENTUM",
        source="technical",
    ),
    MetricSpec(
        key="ADX",
        panel="ADX",
        json_path=("trend", "adx", "adx"),
        label="ADX(14)",
        color="#1f77b4",
        kind="line",
        cli_group="ADX",
        source="technical",
    ),
    MetricSpec(
        key="ADX_POS",
        panel="ADX",
        json_path=("trend", "adx", "adx_pos"),
        label="+DI",
        color="#2ca02c",
        kind="line",
        cli_group="ADX",
        source="technical",
    ),
    MetricSpec(
        key="ADX_NEG",
        panel="ADX",
        json_path=("trend", "adx", "adx_neg"),
        label="-DI",
        color="#d62728",
        kind="line",
        cli_group="ADX",
        source="technical",
    ),
    MetricSpec(
        key="AROON_UP",
        panel="TREND",
        json_path=("trend", "aroon", "aroon_up"),
        label="AROON_UP",
        color=COLOR_TREND,
        kind="line",
        cli_group="TREND",
        source="technical",
    ),
    MetricSpec(
        key="AROON_DOWN",
        panel="TREND",
        json_path=("trend", "aroon", "aroon_down"),
        label="AROON_DOWN",
        color=COLOR_TREND,
        kind="line",
        cli_group="TREND",
        source="technical",
    ),
    MetricSpec(
        key="AROON_INDICATOR",
        panel="TREND",
        json_path=("trend", "aroon", "aroon_indicator"),
        label="AROON_INDICATOR",
        color=COLOR_TREND,
        kind="line",
        cli_group="TREND",
        source="technical",
    ),
    MetricSpec(
        key="CCI",
        panel="TREND",
        json_path=("trend", "cci", "cci"),
        label="CCI",
        color=COLOR_TREND,
        kind="line",
        cli_group="TREND",
        source="technical",
    ),
    MetricSpec(
        key="DPO",
        panel="TREND",
        json_path=("trend", "dpo", "dpo"),
        label="DPO",
        color=COLOR_TREND,
        kind="line",
        cli_group="TREND",
        source="technical",
    ),
    MetricSpec(
        key="EMA_INDICATOR",
        panel="TREND",
        json_path=("trend", "ema", "ema_indicator"),
        label="EMA_INDICATOR",
        color=COLOR_TREND,
        kind="line",
        cli_group="TREND",
        source="technical",
    ),
    MetricSpec(
        key="ICHIMOKU_CONVERSION_LINE",
        panel="TREND",
        json_path=("trend", "ichimoku", "ichimoku_conversion_line"),
        label="ICHIMOKU_CONVERSION_LINE",
        color=COLOR_TREND,
        kind="line",
        cli_group="TREND",
        source="technical",
    ),
    MetricSpec(
        key="ICHIMOKU_BASE_LINE",
        panel="TREND",
        json_path=("trend", "ichimoku", "ichimoku_base_line"),
        label="ICHIMOKU_BASE_LINE",
        color=COLOR_TREND,
        kind="line",
        cli_group="TREND",
        source="technical",
    ),
    MetricSpec(
        key="ICHIMOKU_A",
        panel="TREND",
        json_path=("trend", "ichimoku", "ichimoku_a"),
        label="ICHIMOKU_A",
        color=COLOR_TREND,
        kind="line",
        cli_group="TREND",
        source="technical",
    ),
    MetricSpec(
        key="ICHIMOKU_B",
        panel="TREND",
        json_path=("trend", "ichimoku", "ichimoku_b"),
        label="ICHIMOKU_B",
        color=COLOR_TREND,
        kind="line",
        cli_group="TREND",
        source="technical",
    ),
    MetricSpec(
        key="KST",
        panel="TREND",
        json_path=("trend", "kst", "kst"),
        label="KST",
        color=COLOR_TREND,
        kind="line",
        cli_group="TREND",
        source="technical",
    ),
    MetricSpec(
        key="KST_SIG",
        panel="TREND",
        json_path=("trend", "kst", "kst_sig"),
        label="KST_SIG",
        color=COLOR_TREND,
        kind="line",
        cli_group="TREND",
        source="technical",
    ),
    MetricSpec(
        key="KST_DIFF",
        panel="TREND",
        json_path=("trend", "kst", "kst_diff"),
        label="KST_DIFF",
        color=COLOR_TREND,
        kind="line",
        cli_group="TREND",
        source="technical",
    ),
    MetricSpec(
        key="MACD",
        panel="MACD",
        json_path=("trend", "macd", "macd"),
        label="MACD",
        color="#1f77b4",
        kind="line",
        cli_group="TREND",
        source="technical",
    ),
    MetricSpec(
        key="MACD_SIGNAL",
        panel="MACD",
        json_path=("trend", "macd", "macd_signal"),
        label="Signal",
        color="#ff7f0e",
        kind="line",
        cli_group="TREND",
        source="technical",
    ),
    MetricSpec(
        key="MACD_HIST",
        panel="MACD",
        json_path=("trend", "macd", "macd_diff"),
        label="Hist",
        color="#2ca02c",
        kind="hist",
        cli_group="TREND",
        source="technical",
        alpha=0.4,
        negative_color="#d62728",
    ),
    MetricSpec(
        key="MASS_INDEX",
        panel="TREND",
        json_path=("trend", "mass_index", "mass_index"),
        label="MASS_INDEX",
        color=COLOR_TREND,
        kind="line",
        cli_group="TREND",
        source="technical",
    ),
    MetricSpec(
        key="PSAR",
        panel="TREND",
        json_path=("trend", "psar", "psar"),
        label="PSAR",
        color=COLOR_TREND,
        kind="line",
        cli_group="TREND",
        source="technical",
    ),
    MetricSpec(
        key="PSAR_UP",
        panel="TREND",
        json_path=("trend", "psar", "psar_up"),
        label="PSAR_UP",
        color=COLOR_TREND,
        kind="line",
        cli_group="TREND",
        source="technical",
    ),
    MetricSpec(
        key="PSAR_DOWN",
        panel="TREND",
        json_path=("trend", "psar", "psar_down"),
        label="PSAR_DOWN",
        color=COLOR_TREND,
        kind="line",
        cli_group="TREND",
        source="technical",
    ),
    MetricSpec(
        key="PSAR_UP_INDICATOR",
        panel="TREND",
        json_path=("trend", "psar", "psar_up_indicator"),
        label="PSAR_UP_INDICATOR",
        color=COLOR_TREND,
        kind="line",
        cli_group="TREND",
        source="technical",
    ),
    MetricSpec(
        key="PSAR_DOWN_INDICATOR",
        panel="TREND",
        json_path=("trend", "psar", "psar_down_indicator"),
        label="PSAR_DOWN_INDICATOR",
        color=COLOR_TREND,
        kind="line",
        cli_group="TREND",
        source="technical",
    ),
    MetricSpec(
        key="SMA14",
        panel="TREND",
        json_path=("trend", "sma", "sma_14"),
        label="SMA14",
        color=COLOR_TREND,
        kind="line",
        cli_group="TREND",
        source="technical",
    ),
    MetricSpec(
        key="SMA20",
        panel="PRICE",
        json_path=("trend", "sma", "sma_20"),
        label="SMA20",
        color="#1f77b4",
        kind="line",
        cli_group="TREND",
        source="technical",
    ),
    MetricSpec(
        key="SMA50",
        panel="PRICE",
        json_path=("trend", "sma", "sma_50"),
        label="SMA50",
        color="#ff7f0e",
        kind="line",
        cli_group="TREND",
        source="technical",
    ),
    MetricSpec(
        key="SMA200",
        panel="PRICE",
        json_path=("trend", "sma", "sma_200"),
        label="SMA200",
        color="#9467bd",
        kind="line",
        cli_group="TREND",
        source="technical",
    ),
    MetricSpec(
        key="STC",
        panel="TREND",
        json_path=("trend", "stc", "stc"),
        label="STC",
        color=COLOR_TREND,
        kind="line",
        cli_group="TREND",
        source="technical",
    ),
    MetricSpec(
        key="TRIX",
        panel="TREND",
        json_path=("trend", "trix", "trix"),
        label="TRIX",
        color=COLOR_TREND,
        kind="line",
        cli_group="TREND",
        source="technical",
    ),
    MetricSpec(
        key="VORTEX_POS",
        panel="TREND",
        json_path=("trend", "vortex", "vortex_indicator_pos"),
        label="VORTEX_POS",
        color=COLOR_TREND,
        kind="line",
        cli_group="TREND",
        source="technical",
    ),
    MetricSpec(
        key="VORTEX_NEG",
        panel="TREND",
        json_path=("trend", "vortex", "vortex_indicator_neg"),
        label="VORTEX_NEG",
        color=COLOR_TREND,
        kind="line",
        cli_group="TREND",
        source="technical",
    ),
    MetricSpec(
        key="VORTEX_DIFF",
        panel="TREND",
        json_path=("trend", "vortex", "vortex_indicator_diff"),
        label="VORTEX_DIFF",
        color=COLOR_TREND,
        kind="line",
        cli_group="TREND",
        source="technical",
    ),
    MetricSpec(
        key="WMA",
        panel="TREND",
        json_path=("trend", "wma", "wma"),
        label="WMA",
        color=COLOR_TREND,
        kind="line",
        cli_group="TREND",
        source="technical",
    ),
    MetricSpec(
        key="ATR",
        panel="VOLATILITY",
        json_path=("volatility", "atr", "average_true_range"),
        label="ATR",
        color=COLOR_VOLATILITY,
        kind="line",
        cli_group="VOLATILITY",
        source="technical",
    ),
    MetricSpec(
        key="BBANDS_HBAND",
        panel="VOLATILITY",
        json_path=("volatility", "bbands", "bollinger_hband"),
        label="BBANDS_HBAND",
        color=COLOR_VOLATILITY,
        kind="line",
        cli_group="VOLATILITY",
        source="technical",
    ),
    MetricSpec(
        key="BBANDS_LBAND",
        panel="VOLATILITY",
        json_path=("volatility", "bbands", "bollinger_lband"),
        label="BBANDS_LBAND",
        color=COLOR_VOLATILITY,
        kind="line",
        cli_group="VOLATILITY",
        source="technical",
    ),
    MetricSpec(
        key="BBANDS_MAVG",
        panel="VOLATILITY",
        json_path=("volatility", "bbands", "bollinger_mavg"),
        label="BBANDS_MAVG",
        color=COLOR_VOLATILITY,
        kind="line",
        cli_group="VOLATILITY",
        source="technical",
    ),
    MetricSpec(
        key="BBANDS_PBAND",
        panel="VOLATILITY",
        json_path=("volatility", "bbands", "bollinger_pband"),
        label="BBANDS_PBAND",
        color=COLOR_VOLATILITY,
        kind="line",
        cli_group="VOLATILITY",
        source="technical",
    ),
    MetricSpec(
        key="BBANDS_WBAND",
        panel="VOLATILITY",
        json_path=("volatility", "bbands", "bollinger_wband"),
        label="BBANDS_WBAND",
        color=COLOR_VOLATILITY,
        kind="line",
        cli_group="VOLATILITY",
        source="technical",
    ),
    MetricSpec(
        key="BBANDS_HBAND_INDICATOR",
        panel="VOLATILITY",
        json_path=("volatility", "bbands", "bollinger_hband_indicator"),
        label="BBANDS_HBAND_INDICATOR",
        color=COLOR_VOLATILITY,
        kind="line",
        cli_group="VOLATILITY",
        source="technical",
    ),
    MetricSpec(
        key="BBANDS_LBAND_INDICATOR",
        panel="VOLATILITY",
        json_path=("volatility", "bbands", "bollinger_lband_indicator"),
        label="BBANDS_LBAND_INDICATOR",
        color=COLOR_VOLATILITY,
        kind="line",
        cli_group="VOLATILITY",
        source="technical",
    ),
    MetricSpec(
        key="DONCHIAN_HBAND",
        panel="VOLATILITY",
        json_path=("volatility", "donchian", "donchian_channel_hband"),
        label="DONCHIAN_HBAND",
        color=COLOR_VOLATILITY,
        kind="line",
        cli_group="VOLATILITY",
        source="technical",
    ),
    MetricSpec(
        key="DONCHIAN_LBAND",
        panel="VOLATILITY",
        json_path=("volatility", "donchian", "donchian_channel_lband"),
        label="DONCHIAN_LBAND",
        color=COLOR_VOLATILITY,
        kind="line",
        cli_group="VOLATILITY",
        source="technical",
    ),
    MetricSpec(
        key="DONCHIAN_MBAND",
        panel="VOLATILITY",
        json_path=("volatility", "donchian", "donchian_channel_mband"),
        label="DONCHIAN_MBAND",
        color=COLOR_VOLATILITY,
        kind="line",
        cli_group="VOLATILITY",
        source="technical",
    ),
    MetricSpec(
        key="DONCHIAN_PBAND",
        panel="VOLATILITY",
        json_path=("volatility", "donchian", "donchian_channel_pband"),
        label="DONCHIAN_PBAND",
        color=COLOR_VOLATILITY,
        kind="line",
        cli_group="VOLATILITY",
        source="technical",
    ),
    MetricSpec(
        key="DONCHIAN_WBAND",
        panel="VOLATILITY",
        json_path=("volatility", "donchian", "donchian_channel_wband"),
        label="DONCHIAN_WBAND",
        color=COLOR_VOLATILITY,
        kind="line",
        cli_group="VOLATILITY",
        source="technical",
    ),
    MetricSpec(
        key="KELTNER_HBAND",
        panel="VOLATILITY",
        json_path=("volatility", "keltner", "keltner_channel_hband"),
        label="KELTNER_HBAND",
        color=COLOR_VOLATILITY,
        kind="line",
        cli_group="VOLATILITY",
        source="technical",
    ),
    MetricSpec(
        key="KELTNER_LBAND",
        panel="VOLATILITY",
        json_path=("volatility", "keltner", "keltner_channel_lband"),
        label="KELTNER_LBAND",
        color=COLOR_VOLATILITY,
        kind="line",
        cli_group="VOLATILITY",
        source="technical",
    ),
    MetricSpec(
        key="KELTNER_MBAND",
        panel="VOLATILITY",
        json_path=("volatility", "keltner", "keltner_channel_mband"),
        label="KELTNER_MBAND",
        color=COLOR_VOLATILITY,
        kind="line",
        cli_group="VOLATILITY",
        source="technical",
    ),
    MetricSpec(
        key="KELTNER_PBAND",
        panel="VOLATILITY",
        json_path=("volatility", "keltner", "keltner_channel_pband"),
        label="KELTNER_PBAND",
        color=COLOR_VOLATILITY,
        kind="line",
        cli_group="VOLATILITY",
        source="technical",
    ),
    MetricSpec(
        key="KELTNER_WBAND",
        panel="VOLATILITY",
        json_path=("volatility", "keltner", "keltner_channel_wband"),
        label="KELTNER_WBAND",
        color=COLOR_VOLATILITY,
        kind="line",
        cli_group="VOLATILITY",
        source="technical",
    ),
    MetricSpec(
        key="KELTNER_HBAND_INDICATOR",
        panel="VOLATILITY",
        json_path=("volatility", "keltner", "keltner_channel_hband_indicator"),
        label="KELTNER_HBAND_INDICATOR",
        color=COLOR_VOLATILITY,
        kind="line",
        cli_group="VOLATILITY",
        source="technical",
    ),
    MetricSpec(
        key="KELTNER_LBAND_INDICATOR",
        panel="VOLATILITY",
        json_path=("volatility", "keltner", "keltner_channel_lband_indicator"),
        label="KELTNER_LBAND_INDICATOR",
        color=COLOR_VOLATILITY,
        kind="line",
        cli_group="VOLATILITY",
        source="technical",
    ),
    MetricSpec(
        key="ULCER_INDEX",
        panel="VOLATILITY",
        json_path=("volatility", "ulcer_index", "ulcer_index"),
        label="ULCER_INDEX",
        color=COLOR_VOLATILITY,
        kind="line",
        cli_group="VOLATILITY",
        source="technical",
    ),
    MetricSpec(
        key="ACC_DIST_INDEX",
        panel="VOLUME",
        json_path=("volume", "adi", "acc_dist_index"),
        label="ACC_DIST_INDEX",
        color=COLOR_VOLUME,
        kind="line",
        cli_group="VOLUME",
        source="technical",
    ),
    MetricSpec(
        key="CHAIKIN_MONEY_FLOW",
        panel="VOLUME",
        json_path=("volume", "cmf", "chaikin_money_flow"),
        label="CHAIKIN_MONEY_FLOW",
        color=COLOR_VOLUME,
        kind="line",
        cli_group="VOLUME",
        source="technical",
    ),
    MetricSpec(
        key="EASE_OF_MOVEMENT",
        panel="VOLUME",
        json_path=("volume", "eom", "ease_of_movement"),
        label="EASE_OF_MOVEMENT",
        color=COLOR_VOLUME,
        kind="line",
        cli_group="VOLUME",
        source="technical",
    ),
    MetricSpec(
        key="SMA_EASE_OF_MOVEMENT",
        panel="VOLUME",
        json_path=("volume", "eom", "sma_ease_of_movement"),
        label="SMA_EASE_OF_MOVEMENT",
        color=COLOR_VOLUME,
        kind="line",
        cli_group="VOLUME",
        source="technical",
    ),
    MetricSpec(
        key="FORCE_INDEX",
        panel="VOLUME",
        json_path=("volume", "fi", "force_index"),
        label="FORCE_INDEX",
        color=COLOR_VOLUME,
        kind="line",
        cli_group="VOLUME",
        source="technical",
    ),
    MetricSpec(
        key="MONEY_FLOW_INDEX",
        panel="VOLUME",
        json_path=("volume", "mfi", "money_flow_index"),
        label="MONEY_FLOW_INDEX",
        color=COLOR_VOLUME,
        kind="line",
        cli_group="VOLUME",
        source="technical",
    ),
    MetricSpec(
        key="NEGATIVE_VOLUME_INDEX",
        panel="VOLUME",
        json_path=("volume", "nvi", "negative_volume_index"),
        label="NEGATIVE_VOLUME_INDEX",
        color=COLOR_VOLUME,
        kind="line",
        cli_group="VOLUME",
        source="technical",
    ),
    MetricSpec(
        key="OBV",
        panel="OBV",
        json_path=("volume", "obv", "on_balance_volume"),
        label="OBV",
        color="#9467bd",
        kind="line",
        cli_group="VOLUME",
        source="technical",
    ),
    MetricSpec(
        key="VOLUME_PRICE_TREND",
        panel="VOLUME",
        json_path=("volume", "vpt", "volume_price_trend"),
        label="VOLUME_PRICE_TREND",
        color=COLOR_VOLUME,
        kind="line",
        cli_group="VOLUME",
        source="technical",
    ),
    MetricSpec(
        key="VWAP",
        panel="VOLUME",
        json_path=("volume", "vwap", "volume_weighted_average_price"),
        label="VWAP",
        color=COLOR_VOLUME,
        kind="line",
        cli_group="VOLUME",
        source="technical",
    ),
    MetricSpec(
        key="CUMULATIVE_RETURN",
        panel="OTHERS",
        json_path=("others", "cr", "cumulative_return"),
        label="CUMULATIVE_RETURN",
        color=COLOR_OTHERS,
        kind="line",
        cli_group="OTHERS",
        source="technical",
    ),
    MetricSpec(
        key="DAILY_RETURN",
        panel="OTHERS",
        json_path=("others", "dr", "daily_return"),
        label="DAILY_RETURN",
        color=COLOR_OTHERS,
        kind="line",
        cli_group="OTHERS",
        source="technical",
    ),
    MetricSpec(
        key="DAILY_LOG_RETURN",
        panel="OTHERS",
        json_path=("others", "dlr", "daily_log_return"),
        label="DAILY_LOG_RETURN",
        color=COLOR_OTHERS,
        kind="line",
        cli_group="OTHERS",
        source="technical",
    ),
    MetricSpec(
        key="GEX_NET",
        panel="DEALER",
        json_path=("gex_net",),
        label="GEX Net",
        color="#2ca02c",
        kind="hist",
        cli_group="DEALER",
        source="dealer",
        alpha=0.4,
        negative_color="#d62728",
    ),
    MetricSpec(
        key="GEX_TOTAL",
        panel="DEALER",
        json_path=("gex_total",),
        label="GEX Total",
        color="#1f77b4",
        kind="line",
        cli_group="DEALER",
        source="dealer",
    ),
    MetricSpec(
        key="DGPI",
        panel="DEALER",
        json_path=("dgpi",),
        label="DGPI",
        color="#ff7f0e",
        kind="line",
        cli_group="DEALER",
        source="dealer",
    ),
    MetricSpec(
        key="AVG_IV",
        panel="VOL",
        json_path=("metrics", "avg_iv"),
        label="IV",
        color="#1f77b4",
        kind="line",
        cli_group="VOL",
        source="volatility",
    ),
    MetricSpec(
        key="IV_RANK",
        panel="VOL",
        json_path=("metrics", "iv_rank"),
        label="IV Rank",
        color="#ff7f0e",
        kind="line",
        cli_group="VOL",
        source="volatility",
    ),
)


def filter_metrics(requested_groups: Iterable[str]) -> list[MetricSpec]:
    if not requested_groups:
        return []
    ordered: list[MetricSpec] = []
    seen: set[str] = set()
    for group in requested_groups:
        if group in CLI_GROUP_ALIASES:
            allowed = CLI_GROUP_ALIASES[group]
            for metric in METRIC_REGISTRY:
                if metric.key in allowed and metric.key not in seen:
                    ordered.append(metric)
                    seen.add(metric.key)
        else:
            for metric in METRIC_REGISTRY:
                if metric.cli_group == group and metric.key not in seen:
                    ordered.append(metric)
                    seen.add(metric.key)
    return ordered


def select_panels(metrics: Iterable[MetricSpec], available_metric_keys: set[str]) -> list[str]:
    panels = {"PRICE"}
    for metric in metrics:
        if metric.key in available_metric_keys:
            panels.add(metric.panel)
    ordered: list[str] = []
    for key in PANEL_ORDER:
        if key in panels:
            ordered.append(key)
    return ordered
